feat: add build to ci cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -112,7 +112,7 @@ jobs:
         run: pnpm build
 
       - name: List files after build (debugging)
-        run: ls -al .dist || echo ".dist directory not found"
+        run: find . -type d -name "build" -print || echo "Build directory not found"
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
