feat: add build to ci cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -100,14 +100,25 @@ jobs:
         with:
           run_install: true
 
+      - name: Cache .next/cache
+        uses: actions/cache@v4
+        with:
+          path: .next/cache
+          key: ${{ runner.os }}-next-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-next-cache-
+
       - name: Build App
         run: pnpm build
+
+      - name: List files after build (debugging)
+        run: ls || ls -al .next || echo ".next directory not found"
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
         with:
           name: app-build
-          path: .next
+          path: ./.next
 
   docker_image:
     runs-on: ubuntu-latest
@@ -131,7 +142,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: app-build
-          path: .next
+          path: ./.next
 
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
