feat: add build to ci cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -112,7 +112,7 @@ jobs:
         run: pnpm build
 
       - name: List files after build (debugging)
-        run: ls || ls -al .next || echo ".next directory not found"
+        run: ls -al .next || echo ".next directory not found"
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
